language: "en-US"

reviews:
  profile: "chill"
  high_level_summary: true
  auto_review:
    enabled: true
  tools:
    eslint:
      enabled: true
    ruff:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true

knowledge_base:
  code_guidelines:
    enabled: true
  filePatterns:
    - "**/*.md"
