repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.2.4
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome"]
        files: ^front/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: [--fix]
        files: ^api/.*\.py$

      - id: ruff-format
        files: ^api/.*\.py$

  - repo: local
    hooks:
      - id: generate-openapi-ts
        name: Generate OpenAPI typescript files
        entry: bun run orval
        language: system
        pass_filenames: false
        files: api/openapi.json
