[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]~=0.116",
    "httpx~=0.28",
    "tensorflow~=2.15",
    "transformers[tf]~=4.56",
    "sqlmodel==0.0.24",
    "timm~=1.0",
    "torch~=2.8",
    "alembic>=1.16"
]

[dependency-groups]
dev = [
    "mypy~=1.17",
]
