name: API

on:
  pull_request:
  push:

jobs:
  build:
    defaults:
      run:
        working-directory: "./api"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.12.0

      - name: Install dependencies
        run: devbox run -- uv sync

      - name: Check dependencies
        run: devbox run -- uv run scripts/check_dependencies.py

      - name: Type check
        run: devbox run -- uv run mypy .
