name: API

on:
  pull_request:

defaults:
  run:
    working-directory: api

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.12.0
        with:
          project-path: ./api
      - name: Install dependencies
        run: devbox run -- uv sync
      - name: Check dependencies
        run: devbox run -- uv run scripts/check_dependencies.py
      - name: Static type checking
        run: devbox run -- uv run mypy .
