name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetify-com/devbox-install-action@v0.12.0
      - name: Type check
        run: |
          cd api/
          devbox run -- uv sync
          devbox run -- mypy .
